language: android
android:
  components:
    # The BuildTools version used by your project and SDK
    - tools
    - build-tools-23.0.2
    - android-23
before_script:
  - chmod +x gradlew
  - chmod +wx /usr/local/android-sdk-23.0.2
  - chmod +wx ./android-sdk

env:
  global:
    - ANDROID_HOME=${TRAVIS_BUILD_DIR}/android-sdk
    - PATH=${ANDROID_HOME}/:${ANDROID_HOME}/tools/:${ANDROID_HOME}/platform-tools/:${PATH}

before_install:
  - cp -R /usr/local/android-sdk-23.0.2 ./android-sdk