language: android
android:
  components:
    # The BuildTools version used by your project and SDK
    - tools
    - build-tools-19.1.0
    - android-19
    - sys-img-armeabi-v7a-android-19
before_script:
  - chmod +x gradlew